from __future__ import annotations

EXIFTOOL_MISSING = "exiftool_missing"
METADATA_READ_FAILED = "metadata_read_failed"
CAPTURE_TIME_MISSING = "capture_time_missing"
UNSUPPORTED_DNG_SOURCE = "unsupported_dng_source"
TARGET_CONFLICT = "target_conflict"
TARGET_EXISTS = "target_exists"
INVALID_FILENAME = "invalid_filename"
METADATA_VERSION_UNSUPPORTED = "metadata_version_unsupported"
METADATA_WRITE_FAILED = "metadata_write_failed"
DIRECTORY_NO_SUPPORTED_SOURCES = "directory_no_supported_sources"
WORKSPACE_NOT_FOUND = "workspace_not_found"
WORKSPACE_PATH_INVALID = "workspace_path_invalid"
SIDECAR_AMBIGUOUS = "sidecar_ambiguous"
ARCHIVE_TARGET_EXISTS = "archive_target_exists"
ARCHIVE_NAME_TARGET_EXISTS = "archive_name_target_exists"
ARCHIVE_MISSING_METADATA = "archive_missing_metadata"
METADATA_DEVIATION = "metadata_deviation"
POST_PROCESSOR_REFERENCE_RISK = "post_processor_reference_risk"
